### ISSUE TITLE
Error about lanch and accelerate

### ISSUE THREAD

**Issue by Xnhyacinth** [twinkle0331/LGTM#5]
Hi @twinkle0331 , I read your paper with great interest, and I would like to keep up with your work and use it. But when use `accelerate launch` instead of `python -m torch.distributed.launch`, it will be error with ''exp_avg.mul_(beta1).add_(1.0 - beta1, grad) RuntimeError: The size of tensor a (109484548) must match the size of tensor b (768) at non-singleton dimension 1". 

I have a feeling its the accelerate library and when I go to T5 with this method it gets other errors, what's even stranger is that after prepare the optimizer parameter becomes empty.

**Comment by twinkle0331** [comment]
I haven't tried it with distributed training, the error may be brought by the accelerate library. Maybe you could print the tensor shape with or without "accelerate launch" and find the differences. For T5, you can try the normal training pipeline first(e.g. without distributed training and simple fine-tuning) and then modify the code with our codes. The core operation is how to perturb the gradient and update the parameters, those operations may be slightly different under different libraries.

**Comment by Xnhyacinth** [comment]
That's true, that's why I gave up using the accelerate library and rewrote the code, thanks for the reply, I'll try to do more experiments and compare!

**Comment by twinkle0331** [comment]
Run with "python -m torch.distributed.launch" seems to work fine. [Previous issue](https://github.com/twinkle0331/LGTM/issues/4) only shows error when saving the model to directory.

**Comment by Xnhyacinth** [comment]
> 

yes! I use it, it is okay. Just 'accelerate launch' is not fine.
